### ISSUE TITLE
Feedback issue with RTs

### ISSUE THREAD

**Issue by richranallo** [invinst/ResponseBot#2]
Just noticed this when I retweeted a @CPDPbot message involving Jason Van Dyke; the bot appears to have detected that as me tweeting _at_ it and then replied with Van Dyke's complaint stats. It may be necessary to filter triggering tweets to detect this.

**Comment by cpdbop** [comment]
Nice catch! We will fix this on CPDB bot

**Comment by cpdbop** [comment]
@Polisurgist we deployed the fix on CPDB bot
