### ISSUE TITLE
ResponseBot repository got rebased after being published.

### ISSUE THREAD

**Issue by kfogel** [invinst/ResponseBot#4]
When this repository was initially published, it had one commit:

```
commit 8f01ce6f6f8d017246caf0e87dc81c3b45875121
Author: Huy Nguyen+Giang Nguyen <...omitted...>
Date:   Sat May 7 10:50:37 2016 +0700

    Initial commit
```

I submitted [pull request 1](https://github.com/invinst/ResponseBot/pull/1) based on that commit.

But _now_ when I look at the history, the initial commit is different:

```
commit 0aad906f7abcd5081f87776a11fbee3ec42ddb27
Author: Huy Nguyen+Giang Nguyen <...omitted...>
Date:   Sat May 7 10:50:37 2016 +0700

    Initial commit
```

And I can see that the contents (as compared to the old initial commit) are very different.  In the new version of the initial commit, there is a new file, `tests/unit_tests/models/test_tweet_filter.py`, and there are differences in 17 other files.

Now I'm worried :-).  Is it going to get rebased again?  Is this repository stable enough to use?

If a repository is rebased after it is published, that creates a problem everyone else who cloned that repository and has local branches or local changes in their clone.  See this section of the `git-rebase` manual page:

```
RECOVERING FROM UPSTREAM REBASE
    Rebasing (or any other form of rewriting) a branch that others
    have based work on is a bad idea: anyone downstream of it is
    forced to manually fix their history. This section explains
    how to do the fix from the downstream’s point of view. The
    real fix, however, would be to avoid rebasing the upstream in
    the first place.
```

**Comment by cpdbop** [comment]
@kfogel Sorry for the inconvenience, we did push a change in the initial commit, please rebase your branch with the new master. Thanks for noticing us, we will avoid doing that in the future.

**Comment by kfogel** [comment]
Will do!  Thanks for clarifying.

**Comment by giang-nghg** [comment]
@kfogel We'll re-apply the changes from [your PR](https://github.com/invinst/ResponseBot/pull/1/commits), since it's our fault that it got closed :)
